# Generated by Django 5.2.15 on 2026-06-09 14:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In review'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_uri', models.TextField()),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size_bytes', models.PositiveBigIntegerField()),
                ('change_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='approvals.document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='approvals.documentversion'),
        ),
        migrations.CreateModel(
            name='DocumentWorkflow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_mode', models.CharField(choices=[('sequential', 'Sequential'), ('parallel', 'Parallel')], max_length=30)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_review', 'In review'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='not_started', max_length=30)),
                ('current_stage_number', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='approvals.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentReviewAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_number', models.PositiveIntegerField()),
                ('step_order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_assignments', to='approvals.documentversion')),
                ('document_workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='approvals.documentworkflow')),
            ],
            options={
                'ordering': ['stage_number', 'step_order'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='approvals.organization'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('submitter', 'Submitter'), ('reviewer', 'Reviewer')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='approvals.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_action', to='approvals.documentreviewassignment')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_actions', to='approvals.document')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_actions', to='approvals.documentversion')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_actions', to='approvals.user')),
            ],
        ),
        migrations.AddField(
            model_name='documentversion',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_versions', to='approvals.user'),
        ),
        migrations.AddField(
            model_name='documentreviewassignment',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_assignments', to='approvals.user'),
        ),
        migrations.AddField(
            model_name='document',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_documents', to='approvals.user'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='approvals.document')),
                ('document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='approvals.documentversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='approvals.organization')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='approvals.user')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('approval_mode', models.CharField(choices=[('sequential', 'Sequential'), ('parallel', 'Parallel')], default='sequential', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workflow_templates', to='approvals.user')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='approvals.organization')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_number', models.PositiveIntegerField()),
                ('step_order', models.PositiveIntegerField()),
                ('is_required', models.BooleanField(default=True)),
                ('due_in_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_steps', to='approvals.user')),
                ('workflow_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approvals.workflowtemplate')),
            ],
            options={
                'ordering': ['stage_number', 'step_order'],
            },
        ),
        migrations.AddField(
            model_name='documentworkflow',
            name='workflow_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_workflows', to='approvals.workflowtemplate'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('organization', 'email'), name='unique_user_email_per_org'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='unique_document_version_number'),
        ),
        migrations.AddConstraint(
            model_name='documentreviewassignment',
            constraint=models.UniqueConstraint(fields=('document_workflow', 'reviewer', 'document_version', 'stage_number'), name='unique_assignment_reviewer_version_stage'),
        ),
        migrations.AddConstraint(
            model_name='documentreviewassignment',
            constraint=models.UniqueConstraint(fields=('document_workflow', 'step_order', 'document_version'), name='unique_assignment_order_per_workflow_version'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'status'], name='approvals_d_organiz_4d9656_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['submitter', 'created_at'], name='approvals_d_submitt_1bf045_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['document', 'created_at'], name='approvals_a_documen_957de8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['organization', 'created_at'], name='approvals_a_organiz_125adf_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['event_type', 'created_at'], name='approvals_a_event_t_10a98d_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowtemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_workflow_template_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='workflowstep',
            constraint=models.UniqueConstraint(fields=('workflow_template', 'step_order'), name='unique_step_order_per_template'),
        ),
        migrations.AddConstraint(
            model_name='workflowstep',
            constraint=models.UniqueConstraint(fields=('workflow_template', 'reviewer', 'stage_number'), name='unique_reviewer_per_template_stage'),
        ),
    ]
